import { readFile, writeFile, mkdir } from 'node:fs/promises';
import path from 'node:path';
import { parseArgs } from 'node:util';
import { fileURLToPath } from 'node:url';
import { configFromEnv } from './config.mjs';
import { createCounter, summarize } from './metrics.mjs';
import { search, loadRecords } from './engine.mjs';
import { compareTaskUsage } from './task-usage.mjs';
import { auditRecords } from './audit.mjs';
import { expand } from './expansion.mjs';
import { expandContext } from './context.mjs';
import { selectedCandidates } from './selection.mjs';

const { values: opts, positionals } = parseArgs({ allowPositionals: true, options: {
  root: { type: 'string' }, input: { type: 'string' }, data: { type: 'string' },
  out: { type: 'string' }, experiment: { type: 'string' }, labels: { type: 'string' },
  'task-usage': { type: 'string' },
  verify: { type: 'boolean', default: false },
} });
const command = positionals[0];

function csv(rows) {
  const keys = ['id', 'source_retrieval_id', 'operation', 'timestamp', 'root', 'status', 'mode', 'source', 'experiment', 'baseline_response_tokens',
    'filtered_response_tokens', 'actual_response_tokens', 'paired_tokens_saved', 'paired_reduction_pct',
    'actual_vs_baseline_tokens_saved', 'jev_known_input_tokens', 'jev_known_output_tokens',
    'jev_missing_usage_calls', 'retrieval_ms', 'jev_wall_ms', 'total_ms'];
  const escape = x => `"${String(x ?? '').replaceAll('"', '""')}"`;
  return [keys.join(','), ...rows.map(r => {
    const flat = { ...r, ...r.metrics, ...r.timing, jev_known_input_tokens: r.jev.known_input_tokens,
      jev_known_output_tokens: r.jev.known_output_tokens, jev_missing_usage_calls: r.jev.missing_usage_calls };
    return keys.map(k => escape(flat[k])).join(',');
  })].join('\n') + '\n';
}

// Labels are source-line anchors, not judgments generated by Jev itself.
export function quality(records, labels) {
  return records.map(r => {
    const anchors = labels[r.experiment];
    if (!anchors || r.status !== 'ok' || r.mode === 'baseline' || r.mode === 'expansion') return { id: r.id, evaluated: false };
    const relevant = anchors.filter(a => a.relevant === true);
    const covers = (c, a) => c.file === a.file && c.start_line <= a.line && c.end_line >= a.line;
    const candidates = r.retrieval.candidates;
    const selected = selectedCandidates(r);
    const retrieved = relevant.filter(a => candidates.some(c => covers(c, a)));
    const retained = retrieved.filter(a => selected.some(c => covers(c, a)));
    return { id: r.id, experiment: r.experiment, evaluated: true,
      relevant_anchors: relevant.length, retrieved_relevant_anchors: retrieved.length,
      retained_relevant_anchors: retained.length,
      retrieval_recall: relevant.length ? retrieved.length / relevant.length : null,
      filter_recall_given_retrieval: retrieved.length ? retained.length / retrieved.length : null,
      end_to_end_anchor_recall: relevant.length ? retained.length / relevant.length : null };
  });
}

async function main() {
  if (!['search', 'expand', 'expand-context', 'benchmark', 'report'].includes(command)) {
    throw new Error('Usage: node src/cli.mjs search|expand|expand-context|benchmark --input FILE [--root DIR] [--data DIR] | report --data DIR --out DIR [--labels FILE]');
  }
  if (command === 'report') {
    if (!opts.data) throw new Error('--data is required.');
    let records = await loadRecords(opts.data);
    if (opts.experiment) records = records.filter(r => r.experiment === opts.experiment);
    const summary = summarize(records);
    if (opts.labels) summary.quality = quality(records, JSON.parse(await readFile(opts.labels, 'utf8')));
    if (opts['task-usage']) summary.complete_task_comparison = compareTaskUsage(JSON.parse(await readFile(opts['task-usage'], 'utf8')));
    if (opts.verify) {
      summary.audit = await auditRecords(opts.data, records);
      if (!summary.audit.all_successful_runs_verified) process.exitCode = 1;
    }
    if (opts.out) {
      await mkdir(opts.out, { recursive: true });
      await writeFile(path.join(opts.out, 'summary.json'), JSON.stringify(summary, null, 2));
      await writeFile(path.join(opts.out, 'runs.csv'), csv(records));
    }
    console.log(JSON.stringify(summary, null, 2));
    return;
  }
  if (!opts.input) throw new Error('--input is required.');
  const config = { ...configFromEnv(opts.root), source: command === 'benchmark' ? 'benchmark' : 'cli',
    experiment: opts.experiment || null };
  if (opts.data) config.dataDir = path.resolve(opts.data);
  const counter = createCounter(config.encoding);
  try {
    const input = JSON.parse(await readFile(opts.input, 'utf8'));
    if (['search', 'expand', 'expand-context'].includes(command)) {
      const operation = command === 'expand-context' ? expandContext : command === 'expand' ? expand : search;
      const result = await operation(input, config, { counter });
      console.log(result.payload);
      console.error(JSON.stringify({ run: result.record.id, directory: result.directory, metrics: result.record.metrics }));
      if (result.isError) process.exitCode = 1;
    } else {
      if (!Array.isArray(input) || !input.length || input.length > 100) throw new Error('Benchmark input must contain 1–100 cases.');
      for (const item of input) {
        if (typeof item.name !== 'string' || !item.search) throw new Error('Each benchmark case needs name and search.');
        const result = await search({ ...item.search, mode: 'filtered' }, { ...config, experiment: item.name }, { counter });
        console.log(JSON.stringify({ name: item.name, run: result.record.id, status: result.record.status,
          metrics: result.record.metrics, jev: result.record.jev, timing: result.record.timing }));
        if (result.isError) { process.exitCode = 1; break; }
      }
    }
  } finally { counter.free(); }
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  main().catch(error => { console.error(error.message); process.exitCode = 1; });
}
